### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by mrn3** [Thammachart/docker-shell-tooling#1]
I hope you don't mind me reaching out like this @Thammachart .  I saw your post on:

https://stackoverflow.com/questions/53337156/appengine-whats-the-timeout-for-node-cloud-tasks-handlers/54021646#54021646

I was wondering if you have sample code from that POC you did?

**Comment by Thammachart** [comment]
I no longer use GCP personally now, especially the GAE, and I didn't keep the code, but can recreate. Which part of code do you want?

for Node Request Timeout: Since v14, the default is now `0` (no timeout) instead of 2 minutes. [reference](https://nodejs.org/docs/latest-v14.x/api/http.html#http_server_settimeout_msecs_callback)

I used built-in `http` module in the example, if `express` is what you're using:
``` js
const server = app.listen();
server.setTimeout(86400000);
```

for `/lr`, it's just simple JS built-in `setTimeout(() => { res.end("") }, fromRequest * 1000)`

**Comment by mrn3** [comment]
Thank you so much for this - I will try to implement with this and see if I can reproduce your example.

The thing is, I am still hitting the 2 minute limit on nodejs14.  My app.yaml is:

```
service: transcription
runtime: nodejs
env: flex
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
```
